# Generated by Django 4.2.4 on 2024-05-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/properties'),
        ),
    ]
