# Generated by Django 4.2.4 on 2024-05-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_alter_properties_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='year_built',
            field=models.IntegerField(blank=True),
        ),
    ]
