# Generated by Django 4.2.4 on 2024-05-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_alter_properties_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='location',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='year_built',
        ),
    ]
