# Generated by Django 4.2.4 on 2024-05-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0004_remove_properties_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='images',
            field=models.ImageField(blank=True, upload_to='properties'),
        ),
    ]
