# Generated by Django 5.0.6 on 2024-05-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0006_properties_featured_alter_properties_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='amentities',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='featured',
        ),
        migrations.AddField(
            model_name='properties',
            name='location',
            field=models.CharField(blank=True, default='Nairobi', max_length=100),
        ),
    ]
