# Generated by Django 4.2.4 on 2024-05-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0007_alter_properties_images'),
        ('realtor', '0007_remove_properties_amentities_and_more'),
    ]

    operations = [
    ]
