# Generated by Django 4.2.4 on 2024-05-10 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0008_merge_20240510_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='features',
        ),
        migrations.AddField(
            model_name='properties',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='properties',
            name='images',
            field=models.ImageField(upload_to='properties'),
        ),
    ]
