# Generated by Django 4.2.4 on 2024-05-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0009_remove_properties_features_properties_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.FloatField(),
        ),
    ]
